version: '3.3'

services:
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app-net
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  redis_data:
